services:
  mysqldb:
    image: mysql
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      # MYSQL_DATABASE: invoice_api
      # MYSQL_USER: root
      # MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  invoice_api:
    container_name: invoice_api_container
    # build: .
    image: invoice_app
    # volumes:
    #   - ./invoice_api:/code
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3307
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: invoice_api
      SERVICE_TAGS: prod
      SERVICE_NAME: invoice_apiservice
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge